server:
  port: 10000

springdoc:
  api-docs:
    enable: true
  swagger-ui:
    enable: true

app:
  hosting: AWS

spring:
  application:
    name: mi-app-spring
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  datasource:
    url: jdbc:postgresql://postgres:5432/master_z8ur
    username: ${PRODUCTION_USER_DATABASE}
    password: ${PRODUCTION_PASSWORD_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
