server:
  port: 10000

springdoc:
  api-docs:
    enable: true
  swagger-ui:
    enable: true

app:
  hosting: AWS

spring:
  application:
    name: mi-app-spring

  datasource:
    url: jdbc:postgresql://postgres-server:5432/master_z8ur
    username: ${PRODUCTION_USER_DATABASE}
    password: ${PRODUCTION_PASSWORD_DATABASE}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate