name: iwvg-devops-villa-montoya-juan-diego
services:
  devops:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: devops:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      # SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/master_z8ur
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/master_z8ur
    networks:
      - master

networks:
  master:
    external: true

#en la raiz del proyecto
#cd .docker
#> docker compose up --build -d
