name: iwvg-devops-villa-montoya-juan-diego
services:
  devops:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: devops:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db-master
      SPRING_DATASOURCE_USERNAME: master
      SPRING_DATASOURCE_PASSWORD: master
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - master

networks:
  master:
    external: true

#> docker compose up --build -d
