name: CD Staging
on:
  push:
    branches: ['staging']

env:
  REPOSITORY: ${{ github.repository }}
  GHCR_URL: ghcr.io

jobs:
  cd:
    name: Build & Push GitHub Package & Deploy on Render Docker Image
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: ☕ Set up Java
        uses: actions/setup-java@706542d1033282f6a73c09192408e0cb20141cc1
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: 📦 Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.GHCR_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }}

      - name: 🏷️ Set env variables | VERSION Repository | ARTIFACT version from pom | REPO in Lowr Case from Git
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
          echo "REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: 🐳 Build & Push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: |
            ${{ env.GHCR_URL }}/${{ env.REPO_LOWER }}:${{ env.VERSION }}
            ${{ env.GHCR_URL }}/${{ env.REPO_LOWER }}:latest

      - name: 🚀 Deploy on Render
        env:
          RENDER_DEPLOY_HOOK_TOKEN: ${{ secrets.RENDER_DEPLOY_HOOK_TOKEN }}
        run: |
          # Y luego llamarla usando la sintaxis normal de bash
          curl --fail -X POST "https://api.render.com/deploy/${RENDER_DEPLOY_HOOK_TOKEN}" \
          && echo "✅ Deployment succeeded" \
          || (echo "❌ Deployment failed" && exit 1)

      - name: 🔔 Notify Slack on success
        if: success()
        uses: slackapi/slack-github-action@701167a721245643a6d45f78c800c191cb88f28c
        with:
          payload: |
            {
              "text": "✅ *Despliegue Continuo Exitoso!*\n*Repositorio:* ${{ github.repository }}\n*Autor:* ${{ github.actor }}\n*Commit:* ${{ github.sha }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: 🔔 Notify Slack on failure
        if: failure()
        uses: sslackapi/slack-github-action@701167a721245643a6d45f78c800c191cb88f28c
        with:
          payload: |
            {
              "text": "🚨 *Despliegue Continuo Fallido!*\n*Repositorio:* ${{ github.repository }}\n*Autor:* ${{ github.actor }}\n*Commit:* ${{ github.sha }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}